import assert from 'node:assert/strict';
import { normalizedSkeleton, projectPoint, SkeletonOverlay } from '../web/scripts/motion-skeleton.mjs';

assert.deepEqual(projectPoint({ x: 0.25, y: 0.5 }, 640, 480, 640, 480, true), { x: 480, y: 240 });
assert.deepEqual(projectPoint({ x: 0.25, y: 0.5 }, 640, 480, 640, 480, false), { x: 160, y: 240 });
assert.deepEqual(projectPoint({ x: 0.5, y: 0.5 }, 1920, 1080, 390, 700), { x: 195, y: 350 });
assert.equal(projectPoint({ x: 0.5, y: 0.5 }, 0, 480, 390, 700), null);
const result = { model: 'mediapipe', poses: [{ landmarks: Array.from({ length: 33 }, () => ({ x: 0.5, y: 0.5, visibility: 0.9 })) }] };
result.poses[0].landmarks[13].visibility = 0.1;
assert.equal(normalizedSkeleton(result)[7], null);
assert.equal(normalizedSkeleton(result)[5].name, 'left_shoulder');
assert.deepEqual(normalizedSkeleton({ ...result, poses: [...result.poses, ...result.poses] }), []);
assert.deepEqual(normalizedSkeleton({ poses: [] }), []);
let drawn = 0;
let cleared = 0;
const context = { setTransform() {}, clearRect() { cleared++; }, beginPath() {}, moveTo() {}, lineTo() {}, stroke() {}, arc() { drawn++; }, fill() {} };
const canvas = { clientWidth: 640, clientHeight: 480, getContext: () => context };
const video = { videoWidth: 640, videoHeight: 480, readyState: 2 };
const overlay = new SkeletonOverlay(canvas, video);
overlay.update(result, 0);
overlay.draw(100);
assert.ok(drawn > 0);
drawn = 0;
overlay.draw(251);
assert.equal(drawn, 0);
assert.equal(cleared, 2);
overlay.update(result, 300);
video.readyState = 0;
overlay.draw(310);
assert.equal(drawn, 0);
console.log('Skeleton: mirrored/cropped coordinates, missing joints, multiple people, stale frames and stopped video passed.');
