const assert = require("node:assert/strict");
require("../web/scripts/operations-service.js");

(async () => {
  const values = new Map([["boxing_auth", "untouched-auth"], ["boxing_staff", "untouched-staff"], ["boxing_settings", "untouched-settings"]]);
  const storage = { getItem: key => values.get(key) ?? null, setItem: (key, value) => values.set(key, value), removeItem: key => values.delete(key) };
  const untouched = new Map(values);
  const disabled = BoxingOperations.create({ storage });
  await assert.rejects(disabled.snapshot(), { code: "NOT_CONNECTED" });
  await assert.rejects(disabled.saveMember({ name: "Blocked", phone: "000" }, "disabled"), { code: "NOT_CONNECTED" });
  assert.deepEqual(values, untouched);
  let actor = { id: "preview-owner", name: "샘플 관리자", role: "CENTER_OWNER" };
  const service = BoxingOperations.create({ enabled: true, storage, actor: () => actor });
  const initial = await service.snapshot();
  assert.equal(initial.referenceDate, "2026-09-18");
  assert.equal(values.has(service.key), false, "Reading seed must not persist it");
  const input = { name: "새 샘플 회원", phone: "010-0000-0100" };
  const results = await Promise.all([service.saveMember(input, "double-click"), service.saveMember(input, "double-click")]);
  assert.equal(results[0].id, results[1].id);
  assert.equal((await service.snapshot()).members.length, initial.members.length + 1);
  await assert.rejects(service.saveMember({ ...input, name: "다른 이름" }, "double-click"), { code: "CONFLICT" });
  const member = await service.saveMember({ ...input, id: results[0].id, name: "수정 이름" }, "edit");
  assert.equal(member.name, "수정 이름");
  const product = await service.saveProduct({ name: "새 횟수권", kind: "COUNT", count: 5, days: 30, price: 50000 }, "product");
  const pass = await service.assignPass({ member_id: member.id, product_id: product.id, start_on: "2026-09-18", end_on: "2026-10-18", reason: "신규" }, "assign");
  const paused = await service.changePass({ id: pass.id, action: "PAUSE", reason: "여행" }, "pause");
  assert.equal(paused.status, "PAUSED");
  const resumed = await service.changePass({ id: pass.id, action: "RESUME", reason: "복귀" }, "resume");
  assert.equal(resumed.end_on, pass.end_on, "Preview does not invent automatic pause extension policy");
  const extended = await service.changePass({ id: pass.id, action: "EXTEND", reason: "승인", end_on: "2026-10-25" }, "extend");
  assert.equal(extended.history.length, 4);
  const visitInput = { member_id: member.id, visited_on: "2026-09-18", reason: "방문" };
  const visits = await Promise.allSettled([service.markAttendance(visitInput, "visit1"), service.markAttendance(visitInput, "visit2")]);
  assert.equal(visits.filter(row => row.status === "fulfilled").length, 1);
  const visit = visits.find(row => row.status === "fulfilled").value;
  await service.cancelAttendance({ id: visit.id, reason: "오입력" }, "cancel-visit");
  assert.deepEqual((await service.snapshot()).workouts, initial.workouts, "Visits never create workout sessions");
  assert.equal((await service.snapshot()).passes.find(row => row.id === pass.id).remaining, 5, "No invented count deduction policy");
  const payment = await service.registerPayment({ member_id: member.id, product_id: product.id, amount: 50000, method: "CARD", status: "PAID", paid_on: "2026-09-18" }, "payment");
  const refund = await service.adjustPayment({ id: payment.id, action: "REFUND", amount: 10000, reason: "입력 기록", on: "2026-09-19" }, "refund");
  assert.equal(refund.status, "PARTIAL_REFUND");
  await assert.rejects(service.adjustPayment({ id: payment.id, action: "REFUND", amount: 50000, reason: "초과", on: "2026-09-19" }, "over-refund"), { code: "VALIDATION" });
  const note = await service.addNote({ member_id: member.id, content: "상담 메모" }, "note");
  assert.equal(note.author_name, actor.name);
  await service.saveCenter({ name: "수정 센터", phone: "010-0000-1000", address: "합성 주소", hours: "09:00–20:00" }, "center-edit");
  const staff = await service.saveStaff({ name: "새 직원", phone: "010-0000-2000", job: "접수", status: "ACTIVE" }, "staff-add");
  await service.saveStaff({ ...staff, status: "INACTIVE" }, "staff-retire");
  assert.equal((await service.snapshot()).center.name, "수정 센터");
  const afterPeople = storage.getItem(service.key);
  service.failNext();
  await assert.rejects(service.saveMember(input, "failed-save"), { code: "UNAVAILABLE" });
  assert.equal(storage.getItem(service.key), afterPeople);
  await assert.rejects(service.markAttendance({ ...visitInput, visited_on: "2026-02-30" }, "bad-date"), { code: "VALIDATION" });
  await assert.rejects(service.markAttendance({ ...visitInput, member_id: "real-user-id" }, "real-id"), { code: "NOT_FOUND" });
  actor = { id: "preview-coach", name: "샘플 코치", role: "COACH" };
  await assert.rejects(service.saveMember(input, "coach-create"), { code: "FORBIDDEN" });
  await assert.rejects(service.registerPayment({}, "coach-pay"), { code: "FORBIDDEN" });
  await assert.rejects(service.saveStaff({}, "coach-staff"), { code: "FORBIDDEN" });
  await assert.rejects(service.saveCenter({}, "coach-center"), { code: "FORBIDDEN" });
  await service.addNote({ member_id: member.id, content: "코치 메모" }, "coach-note");
  actor = { id: member.id, name: member.name, role: "MEMBER" };
  const own = await service.snapshot();
  assert.deepEqual(own.members.map(row => row.id), [member.id]);
  assert.ok(own.payments.every(row => row.member_id === member.id));
  assert.deepEqual(own.notes, []);
  await assert.rejects(service.saveMember(input, "member-save"), { code: "FORBIDDEN" });
  actor = { id: "preview-member-1", name: "샘플 김하나", role: "MEMBER" };
  const profile = await service.saveProfile({ id: "preview-member-2", name: "본인 변경", phone: "010-0000-3333", role: "CENTER_OWNER" }, "self-profile");
  assert.equal(profile.id, actor.id);
  assert.equal(profile.role, undefined);
  await assert.rejects(service.deleteWorkout({ id: "preview-workout-2" }, "other-workout"), { code: "FORBIDDEN" });
  await service.deleteWorkout({ id: "preview-workout-1" }, "own-workout");
  assert.ok((await service.snapshot()).workouts.every(row => row.member_id === actor.id && row.id !== "preview-workout-1"));
  actor = { id: "preview-platform", role: "PLATFORM_ADMIN" };
  await assert.rejects(service.snapshot(), { code: "FORBIDDEN" });
  actor = { id: "preview-owner", name: "샘플 관리자", role: "CENTER_OWNER" };
  await service.setReferenceDate("2026-10-01");
  assert.equal((await service.snapshot()).referenceDate, "2026-10-01");
  await service.deleteMember({ id: member.id, reason: "합성 회원 삭제" }, "delete-member");
  await assert.rejects(service.addNote({ member_id: member.id, content: "삭제 후 메모" }, "deleted-note"), { code: "CONFLICT" });
  await assert.rejects(service.assignPass({ member_id: member.id }, "deleted-pass"), { code: "CONFLICT" });
  await assert.rejects(service.registerPayment({ member_id: member.id }, "deleted-payment"), { code: "CONFLICT" });
  for (const [key, value] of untouched) assert.equal(values.get(key), value);
  values.set(service.key, "{broken");
  await assert.rejects(service.snapshot(), { code: "STORAGE" });
  assert.equal(values.get(service.key), "{broken", "Corruption is never silently overwritten");
  await service.reset();
  assert.deepEqual(values, untouched, "Reset only removes dedicated preview storage");
  console.log("Operations service: isolation, idempotency, member/product/pass/attendance/payment/note flows, failures and role boundaries passed");
})().catch(error => { console.error(error); process.exitCode = 1; });
