import assert from 'node:assert/strict';
import {CoachConversation,coachingSummary,coachingCues} from '../web/scripts/coach-conversation.mjs';

const session={id:'private-session',user_id:'private-member',name:'Private name',started_at:100,ended_at:160,
  feedback_report:JSON.stringify({version:1,status:'experimental',counts:{jab:2,hook:0,uppercut:0,one_two:1},total_points:24,mean_quality:80,events:[{private:'coordinates'}]})};
const summary=coachingSummary(session);
assert.equal(summary.duration_seconds,60);
assert.equal(coachingSummary({started_at:0,ended_at:1,feedback_report:{version:1,duration_ms:500}}).duration_seconds,0.5);
assert.equal(JSON.stringify(summary).includes('private'),false);
assert.equal(summary.events,undefined);
const untracked={...session,feedback_report:{version:1,status:'unavailable',tracking:{total_ms:1500,gaps:[{start_ms:0,end_ms:1500,reason:'no_result'}]}}};
assert.equal(coachingSummary(untracked).tracking_unavailable_seconds,1.5);
assert.match(coachingCues(untracked).join(' '),/약 1.5초/);
assert.equal(coachingSummary(untracked).gaps,undefined);
assert.match(coachingCues(session).join(' '),/관측 근거가 없습니다/);
const guarded={...session,feedback_report:{version:1,status:'experimental',events:[{guard_ratio:1},{guard_ratio:0.2},{guard_ratio:0.3},{guard_ratio:null},{guard_ratio:'0.1'}]}};
assert.deepEqual(coachingSummary(guarded).guard_observations,{evaluated:3,maintained:1,lowered:2});
assert.match(coachingCues(guarded).join(' '),/반복 관측: 2개/);
assert.match(coachingCues(guarded).join(' '),/잘된 점: 1개/);
BoxingI18n.setLanguage('en');
assert.match(coachingCues(guarded).join(' '), /Repeated observation:.*2 movements/);
assert.match(coachingCues(guarded).join(' '), /Positive observation:.*1 movements/);
assert.match(coachingCues(untracked).join(' '), /about 1.5 seconds/);
assert.match(coachingCues(untracked).join(' '), /0.0–1.5 sec \(Analysis gap\)/);
assert.doesNotMatch(coachingCues(guarded).join(' '), /[가-힣]/);
BoxingI18n.setLanguage('ko');
const displayed=[];
const states=[];
let release;
let captured;
const chat=new CoachConversation({session,provider:{reply:request=>{captured=request;return new Promise(resolve=>{release=resolve;});}},onMessage:message=>displayed.push(message),onState:state=>states.push(state)});
const first=chat.send('가드를 어떻게 유지하나요?');
await Promise.resolve();
assert.equal(await chat.send('중복'),false);
assert.equal(captured.language,'ko');
let englishRequest;
const englishChat=new CoachConversation({session,language:'en',provider:{reply:async request=>{englishRequest=request;return {text:'Test reply'};}}});
assert.equal(await englishChat.send('How was my guard?'),true);
assert.equal(englishRequest.language,'en');
englishChat.close();
assert.deepEqual(captured.history,[]);
captured.summary.total_points=999;
release({text:'합성 테스트 응답',total_points:999});
assert.equal(await first,true);
assert.equal(chat.summary.total_points,24);
assert.equal(displayed.length,2);
assert.deepEqual(states,['loading','ready']);
const late=chat.send('늦은 응답');
await Promise.resolve();
chat.close();
release({text:'닫힌 후 테스트 응답'});
assert.equal(await late,false);
assert.equal(displayed.length,2);
assert.equal(chat.messages.length,0);
assert.equal(chat.summary,null);
const timeoutStates=[];
const timeout=new CoachConversation({session,timeoutMs:10,provider:{reply:()=>new Promise(()=>{})},onState:state=>timeoutStates.push(state)});
assert.equal(await timeout.send('시간 초과'),false);
assert.deepEqual(timeoutStates,['loading','timeout']);
assert.equal(timeout.pending,null);
const disconnected=new CoachConversation({session});
assert.equal(await disconnected.send('질문'),false);
const failed=new CoachConversation({session,provider:{reply:()=>Promise.reject(new Error('quota'))}});
assert.equal(await failed.send('실패'),false);
assert.equal(failed.messages.length,0);
assert.equal(await failed.send('x'.repeat(2001)),false);
console.log('Coach interface: minimal summary, single request, immutable score, timeout, disconnect and late response cancellation passed');
const {workoutReport} = await import('../web/scripts/workout-export.mjs');
const exported = workoutReport({id:'round',started_at:1,ended_at:61,feedback_report:{counts:{jab:2},total_points:4}}, {turns:[{asked_at:'2026-09-25T00:00:00Z',answered_at:'2026-09-25T00:00:01Z',question:'안녕 <script>alert(1)</script>',answer:'Hello & welcome'}]});
if (!exported.text.includes('안녕') || !exported.html.includes('&lt;script&gt;') || exported.html.includes('<script>')) throw new Error('Export must preserve Unicode and escape HTML');
if (!workoutReport({id:'missing'},null,true).text) throw new Error('Missing chat must not block export');
const guardReport = workoutReport(guarded, {turns:[]});
assert.match(guardReport.text, /반복 관측: 2개/);
assert.doesNotMatch(guardReport.text, /guard_ratio|"events"|"version"|저장된 피드백 원문|private-session/);
assert.match(guardReport.text, /1분 0초/);
assert.match(workoutReport({id:'missing',feedback_report:{}},null).text, /정보 없음/);
BoxingI18n.setLanguage('en');
const englishReport = workoutReport(guarded, {turns:[]});
assert.match(englishReport.text, /Repeated observation:.*2 movements/);
assert.doesNotMatch(englishReport.text, /[가-힣]/);
BoxingI18n.setLanguage('ko');
