const assert = require("node:assert/strict");
const fs = require("node:fs");
const { browserFixture } = require("./browser_fixture");

(async () => {
  const fixture = await browserFixture();
  const { page } = fixture;
  const errors = [];
  page.on("pageerror", error => errors.push(error.message));
  page.setDefaultTimeout(10000);
  const field = name => page.locator(`dialog [name="${name}"]`);
  const submit = async () => {
    await page.locator('dialog [type="submit"]').click();
    await page.locator("dialog").waitFor({ state: "detached" });
  };
  try {
    await fixture.login();
    await page.locator('[data-view="center"]').click();
    await page.locator('.op-center-shared [name="phone"]').fill('010-0000-7777');
    await page.locator('.op-center-shared [name="address"]').fill('합성 센터 주소');
    await page.locator('.op-center-shared button').click();
    await page.locator('.op-center-message').getByText('저장했습니다.', { exact: true }).waitFor();
    assert.equal(await page.locator('[name="ringCount"], [name="bagCount"]').count(), 0);
    await page.locator('[name="defaultSessionMinutes"]').fill('2');
    await page.locator('[name="defaultSessionSeconds"]').fill('45');
    await page.locator('#centerLocalForm button').click();
    const minuteBox = await page.locator('[name="defaultSessionMinutes"]').boundingBox();
    const secondBox = await page.locator('[name="defaultSessionSeconds"]').boundingBox();
    assert.ok(Math.abs(minuteBox.y - secondBox.y) < 2);
    await page.reload();
    await page.locator('[data-view="center"]').click();
    await page.locator('.op-center-shared [name="address"]').waitFor();
    assert.equal(await page.locator('.op-center-shared [name="address"]').inputValue(), '합성 센터 주소');
    assert.equal(await page.locator('[name="defaultSessionSeconds"]').inputValue(), '45');
    assert.equal(await page.evaluate(() => state.center.defaultSessionDurationSeconds), 165);
    await page.locator('[data-view="dashboard"]').click();
    await page.locator(".op-donut").waitFor();
    assert.equal(await page.locator('[data-view="memberships"]').count(), 0);
    assert.equal(await page.locator(".op-chart-column").count(), 6);
    for (const heading of ["만료 예정", "장기 미방문", "미납 확인", "최근 등록·변경·수납 활동"]) assert.equal(await page.getByRole("heading", { name: heading, exact: true }).count(), 0);
    await page.locator('[data-action="product-new"]').click();
    await field("name").fill("연동 검증 10회권");
    await field("kind").selectOption("COUNT");
    await field("count").fill("10");
    await field("price").fill("100000");
    await submit();
    await page.getByText("연동 검증 10회권", { exact: true }).waitFor();
    await page.locator('[data-view="members"]').click();
    await page.locator('[data-action="member-new"]').click();
    for (const [name, value] of Object.entries({ username: "integratedmember", email: "integration@example.invalid", password: "Synthetic!123", password_confirm: "Synthetic!123", name: "통합 검증 회원", phone: "010-0000-1111" })) await field(name).fill(value);
    await field("product_id").selectOption({ label: "연동 검증 10회권" });
    await submit();
    await page.getByRole("button", { name: "통합 검증 회원", exact: true }).click();
    await page.locator('[data-action="member-tab"][data-id="passes"]').click();
    await page.getByText("10회", { exact: true }).waitFor();
    const initial = await page.evaluate(() => api("/operations"));
    const member = initial.members.find(row => row.name === "통합 검증 회원");
    assert.ok(member);
    assert.equal(initial.passes[0].member_id, member.id);
    await page.locator('[data-view="members"]').click();
    const memberRow = page.locator('tr').filter({ hasText: '통합 검증 회원' });
    await memberRow.waitFor();
    assert.equal(await memberRow.locator('[data-action="member-delete"]').count(), 1);
    await memberRow.locator('[data-action="member-edit"]').click();
    assert.equal(await field('joined_on').count(), 0);
    await field('height_cm').fill('181');
    await field('weight_kg').fill('82');
    await field('training_level').fill('3');
    await field('stance').selectOption('southpaw');
    await field('injury_note').fill('합성 프로필 메모');
    await field('pass_id').selectOption(initial.passes[0].id);
    await field('end_on').fill(initial.referenceDate);
    await field('reason').fill('합성 만료일 수정');
    await submit();
    const edited = await page.evaluate(() => api('/operations'));
    assert.equal(edited.members[0].joined_on, member.joined_on);
    assert.equal(edited.members[0].height_cm, 181);
    assert.equal(edited.members[0].injury_note, '합성 프로필 메모');
    assert.equal(edited.passes[0].end_on, initial.referenceDate);
    assert.ok(edited.passes[0].history.some(row => row.action === 'SET_END'));
    const monthStart = new Date(`${initial.referenceDate.slice(0, 7)}-01T00:00:00Z`);
    monthStart.setUTCMonth(monthStart.getUTCMonth() - 1);
    const paidOn = monthStart.toISOString().slice(0, 10);
    await page.locator('[data-view="payments"]').click();
    await page.locator('[data-action="payment-new"]').click();
    await field("member_id").selectOption(member.id);
    await field("amount").fill("100000");
    await field("method").selectOption('KAKAOPAY');
    await field("paid_on").fill(paidOn);
    await submit();
    for (const amount of ["40000", "60000"]) {
      await page.locator('[data-action="payment-detail"]').click();
      await field("action").selectOption("REFUND");
      await field("amount").fill(amount);
      await field("reason").fill("합성 월별 환불 검증");
      await submit();
    }
    const finances = await page.evaluate(() => api("/operations"));
    assert.equal(finances.revenue.at(-2).net, 100000);
    assert.equal(finances.revenue.at(-1).net, -100000);
    assert.equal(finances.payments[0].adjustments.length, 2);
    assert.equal(finances.payments[0].method, 'KAKAOPAY');
    await page.locator('[data-view="attendance"]').click();
    await page.getByText("결석", { exact: true }).waitFor();
    assert.equal(await page.getByRole('button', { name: '수동 출석', exact: true }).count(), 0);
    assert.ok(await page.locator('.op-calendar [data-weekday="0"]').count() > 1);
    assert.ok(await page.locator('.op-calendar [data-weekday="6"]').count() > 1);
    await page.locator(`[data-action="visit-new"][data-id="${member.id}"]`).click();
    await field("reason").fill("합성 출석 검증");
    await submit();
    await page.locator('.op-badge[data-tone="PRESENT"]').waitFor();
    await page.locator('[data-view="dashboard"]').click();
    await page.locator('.op-donut[aria-label*="출석률 100%"] ').waitFor();
    await page.reload();
    await page.locator('[data-view="dashboard"]').click();
    await page.locator(".op-donut").waitFor();
    assert.equal(await page.evaluate(() => localStorage.getItem("boxingcoach.dev.operations.v1")), null);
    fs.mkdirSync("artifacts/operations-integration", { recursive: true });
    for (const [width, height] of [[1366, 768], [390, 844]]) {
      await page.setViewportSize({ width, height });
      for (const theme of ["dark", "light"]) {
        await page.evaluate(value => document.body.dataset.theme = value, theme);
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
        await page.screenshot({ path: `artifacts/operations-integration/dashboard-${width}-${theme}.png`, fullPage: true });
      }
    }
    await page.setViewportSize({ width: 1366, height: 768 });
    await page.locator('[data-view="members"]').click();
    await page.getByRole("button", { name: "통합 검증 회원", exact: true }).click();
    await page.locator('[data-action="member-delete"]').click();
    await field("reason").fill("합성 회원 삭제 검증");
    await submit();
    const final = await page.evaluate(() => api("/operations"));
    assert.ok(final.members.find(row => row.id === member.id).deleted_on);
    assert.equal(final.passes.length, 1);
    assert.equal(final.attendance.length, 1);
    assert.equal(final.payments.length, 1);
    assert.equal(final.payments[0].status, "REFUNDED");
    assert.equal(final.roster.total, 0);
    assert.deepEqual(errors, []);
    console.log("Live operations: charts, product/member+pass registration, attendance, reload, preserved deletion passed.");
  } finally { await fixture.close(); }
})().catch(error => { console.error(error); process.exitCode = 1; });
