import assert from 'node:assert/strict';
import { classifyTrajectory, PunchRecognizer } from '../web/scripts/motion-recognizer.mjs';

const baseline = { x: 0, y: 0, z: 0 };
const samples = positions => positions.map((position, index) => ({ position: { ...baseline, ...position }, timestamp: index * 80, elbowAngle: position.angle || 100, confidence: 0.9, otherGuard: true }));
const jab = classifyTrajectory(samples([{ z: -0.4 }, { z: -0.8, angle: 165 }, { z: -0.4 }, {}]), baseline);
const hook = classifyTrajectory(samples([{ x: 0.4 }, { x: 0.8 }, { x: 0.4 }, {}]), baseline);
const upper = classifyTrajectory(samples([{ y: -0.4 }, { y: -0.8 }, { y: -0.4 }, {}]), baseline);
assert.equal(jab.label, 'straight');
assert.equal(hook.label, 'hook');
assert.equal(upper.label, 'uppercut');
assert.equal(classifyTrajectory(samples([{ x: 0.05 }, { x: 0.08 }, { x: 0.04 }, {}]), baseline), null);
assert.equal(classifyTrajectory(samples([{ x: 0.4, y: -0.4 }, { x: 0.8, y: -0.8 }, {}, {}]), baseline), null);
const recognizer = new PunchRecognizer();
assert.deepEqual(recognizer.accept(jab, 'left'), []);
const combo = recognizer.accept({ ...jab, start_ms: 200, end_ms: 500 }, 'right');
assert.equal(combo.length, 1);
assert.equal(combo[0].label, 'one_two');
assert.equal(combo[0].components.length, 2);
assert.deepEqual(recognizer.flush(2000), []);
assert.deepEqual(recognizer.accept(jab, 'right'), []);
recognizer.accept(jab, 'left');
assert.equal(recognizer.flush(2000)[0].label, 'jab');
assert.deepEqual(recognizer.flush(3000), []);
const southpaw = new PunchRecognizer({ stance: 'southpaw' });
southpaw.accept(jab, 'right');
assert.equal(southpaw.accept({ ...jab, start_ms: 200, end_ms: 500 }, 'left')[0].label, 'one_two');
const arm = { position: baseline, elbowAngle: 100, confidence: 0.9, guard: true };
recognizer.reset();
for (let timestamp = 0; timestamp <= 1000; timestamp += 50) assert.deepEqual(recognizer.update({ timestamp, valid: true, arms: { left: arm, right: arm } }), []);
recognizer.accept(jab, 'left');
assert.equal(recognizer.update({ timestamp: 1100, valid: false })[0].label, 'jab');
assert.deepEqual(recognizer.flush(3000), []);
assert.deepEqual(recognizer.update({ timestamp: 1000, valid: true, arms: { left: arm, right: arm } }), []);
recognizer.reset();
const emitted = [];
for (let timestamp = 0; timestamp <= 300; timestamp += 50) emitted.push(...recognizer.update({ timestamp, valid: true, arms: { left: arm, right: arm } }));
for (const [timestamp, depth, angle] of [[350, -0.4, 120], [430, -0.8, 165], [510, -0.4, 120], [590, 0, 100]]) {
  emitted.push(...recognizer.update({ timestamp, valid: true, arms: { left: { ...arm, position: { ...baseline, z: depth }, elbowAngle: angle, guard: depth === 0 }, right: arm } }));
}
for (let timestamp = 650; timestamp <= 1800; timestamp += 50) emitted.push(...recognizer.update({ timestamp, valid: true, arms: { left: arm, right: arm } }));
assert.equal(emitted.length, 1);
assert.equal(emitted[0].label, 'jab');
assert.equal(emitted[0].experimental, true);
recognizer.reset();
recognizer.accept(jab, 'left');
recognizer.hands.right.samples = [{timestamp:1000}];
assert.deepEqual(recognizer.flush(1200), []);
const delayedCombo = recognizer.accept({...jab,start_ms:1000,end_ms:1500},'right');
assert.equal(delayedCombo[0].label,'one_two');
recognizer.reset();
recognizer.accept(jab,'left');
recognizer.hands.right.samples = [{timestamp:1000}];
assert.equal(recognizer.flush(2900)[0].label,'jab');
console.log('Experimental motion rules: synthetic trajectories, ambiguity, stance, one-two deduplication, idle and tracking loss passed; not real-world accuracy.');
