import assert from 'node:assert/strict';
import { MotionPipeline } from '../web/scripts/motion-pipeline.mjs';

const workers = [];
const results = [];
const errors = [];
let finishCapture;
let clock = 0;
let closed = 0;
const pipeline = new MotionPipeline({
  workerFactory: () => {
    const worker = { messages: [], postMessage(message) { this.messages.push(message); }, terminate() { this.terminated = true; } };
    workers.push(worker);
    return worker;
  },
  capture: () => new Promise(resolve => { finishCapture = () => resolve({ close() { closed++; } }); }),
  onResult: result => results.push(result), onError: error => errors.push(error), now: () => clock,
});
pipeline.start({ model: 'test' });
assert.equal(await pipeline.submit({}, 0), false);
workers[0].onmessage({ data: { type: 'ready' } });
const first = pipeline.submit({}, 0);
assert.equal(await pipeline.submit({}, 50), false);
finishCapture();
assert.equal(await first, true);
const firstId = workers[0].messages[1].id;
workers[0].onmessage({ data: { type: 'result', id: firstId + 1 } });
assert.equal(results.length, 0);
clock = 32;
workers[0].onmessage({ data: { type: 'result', id: firstId } });
assert.equal(results[0].latencyMs, 32);
workers[0].onmessage({ data: { type: 'result', id: firstId } });
assert.equal(results.length, 1);
assert.equal(await pipeline.submit({}, 30), false);
const pending = pipeline.submit({}, 50);
pipeline.stop();
finishCapture();
assert.equal(await pending, false);
assert.equal(closed, 1);
assert.equal(workers[0].terminated, true);
pipeline.start({ model: 'test' });
workers[0].onmessage({ data: { type: 'ready' } });
assert.equal(pipeline.ready, false);
workers[1].onmessage({ data: { type: 'ready' } });
pipeline.timeoutMs = 10;
const stalled = pipeline.submit({}, 100);
await new Promise(resolve => setTimeout(resolve, 25));
assert.equal(errors.length, 1);
assert.equal(pipeline.ready, false);
finishCapture();
assert.equal(await stalled, false);
assert.equal(closed, 2);
pipeline.stop();
pipeline.start({ model: 'mediapipe', delegate: 'AUTO' });
const gpu = workers.at(-1);
assert.equal(gpu.messages[0].config.delegate, 'GPU');
gpu.onmessage({ data: { type: 'ready' } });
assert.equal(pipeline.delegate, 'GPU');
gpu.onmessage({ data: { type: 'error', message: 'GPU context lost' } });
const cpu = workers.at(-1);
assert.notEqual(cpu, gpu);
assert.equal(gpu.terminated, true);
assert.equal(cpu.messages[0].config.delegate, 'CPU');
assert.equal(errors.length, 1);
gpu.onmessage({ data: { type: 'error', message: 'Late GPU failure' } });
assert.equal(workers.at(-1), cpu);
cpu.onmessage({ data: { type: 'ready' } });
assert.equal(pipeline.delegate, 'CPU');
cpu.onmessage({ data: { type: 'error', message: 'CPU unavailable' } });
assert.equal(errors.length, 2);
assert.equal(pipeline.ready, false);
pipeline.start({ model: 'mediapipe', delegate: 'AUTO' });
const stoppedGpu = workers.at(-1);
pipeline.stop();
stoppedGpu.onmessage({ data: { type: 'error', message: 'Cancelled GPU startup' } });
assert.equal(workers.at(-1), stoppedGpu);
assert.equal(errors.length, 2);
pipeline.timeoutMs = 5000;
pipeline.start({model:'test'});
const freshest = workers.at(-1);
freshest.onmessage({data:{type:'ready'}});
assert.equal(pipeline.offer({frame:0},0),true);
finishCapture();
await Promise.resolve();
assert.equal(pipeline.offer({frame:40},40),true);
assert.equal(pipeline.offer({frame:80},80),true);
assert.equal(pipeline.offer({frame:60},60),false);
assert.equal(freshest.messages.length,2);
freshest.onmessage({data:{type:'result',id:freshest.messages[1].id}});
finishCapture();
await Promise.resolve();
assert.equal(freshest.messages.length,3);
assert.equal(freshest.messages[2].timestamp,80);
pipeline.offer({frame:120},120);
pipeline.stop();
freshest.onmessage({data:{type:'result',id:freshest.messages[2].id}});
assert.equal(freshest.messages.length,3);
console.log('Motion pipeline: no frame backlog, throttling, stale/duplicate results, cancellation and timeout cleanup passed.');
