import assert from 'node:assert/strict';
import { MotionRound } from '../web/scripts/motion-round.mjs';

let output = [];
let delayed = [];
const recognizer = {update:()=>output,flush:()=>delayed};
const round = new MotionRound({startedAt:10000,recognizer});
const event = {id:'jab-1',label:'jab',hand:'left',start_ms:300.8,end_ms:700.9,quality:75,confidence:0.9,points:999};
output = [event,event];
round.update({timestamp:9000,valid:true});
assert.equal(round.totalPoints,0);
round.update({timestamp:11000,valid:true});
assert.equal(round.totalPoints,8);
round.update({timestamp:11200,valid:true});
assert.equal(round.totalPoints,8);
assert.equal(round.feedback(14999),null);
assert.match(round.feedback(15000),/잽 1회/);
assert.equal(round.feedback(20000),null);
delayed = [{...event,id:'jab-2',start_ms:1200,end_ms:1500}];
const report = round.finish(22000);
assert.equal(report.events.length,2);
assert.equal(report.events[0].end_ms,700);
assert.equal(report.duration_ms,12000);
report.events[0].quality=1;
assert.equal(round.finish(30000).events[0].quality,75);
assert.equal(round.finish(30000).duration_ms,12000);
round.update({timestamp:31000,valid:true});
assert.equal(round.totalPoints,16);
assert.equal(round.feedback(32000),null);
const next = new MotionRound({startedAt:33000});
assert.equal(next.totalPoints,0);
assert.equal(next.finish(34000).status,'unavailable');
assert.equal(next.finish(34000).events.length,0);
assert.deepEqual(next.finish(34000).tracking,{gaps:[{start_ms:0,end_ms:1000,reason:'no_result'}],total_ms:1000,truncated:false});
const tracked = new MotionRound({startedAt:0});
tracked.update({timestamp:100,valid:false});
tracked.update({timestamp:200,valid:false});
tracked.update({timestamp:300,valid:true,arms:{}});
tracked.update({timestamp:250,valid:false});
assert.deepEqual(tracked.finish(1000).tracking,{gaps:[{start_ms:0,end_ms:100,reason:'no_result'},{start_ms:100,end_ms:300,reason:'unreliable'},{start_ms:550,end_ms:1000,reason:'no_result'}],total_ms:750,truncated:false});
const bounded = new MotionRound({startedAt:0,recognizer:{update:()=>[],flush:()=>[]}});
for (let index=0;index<500;index++) bounded.update({timestamp:index*100,valid:index%2===0});
const boundedReport = bounded.finish(50000);
assert.equal(boundedReport.tracking.gaps.length,200);
assert.equal(boundedReport.tracking.total_ms,25000);
assert.equal(boundedReport.tracking.truncated,true);
const coached = new MotionRound({startedAt:0,recognizer});
output = [{...event,evidence:{otherGuard:1}}];
coached.update({timestamp:1000,valid:true});
assert.match(coached.feedback(5000),/반대손 가드를 유지/);
output = [{...event,id:'lower-1',start_ms:5100,end_ms:5500,evidence:{otherGuard:0.2}},
  {...event,id:'lower-2',start_ms:5600,end_ms:6000,evidence:{otherGuard:0.3}}];
coached.update({timestamp:6500,valid:true});
assert.match(coached.feedback(10000),/가드 위치를 확인/);
delayed=[];
assert.equal(coached.finish(11000).events[0].evidence,undefined);
assert.deepEqual(coached.finish(11000).events.map(event=>event.guard_ratio),[1,0.2,0.3]);
const perEvent = new MotionRound({startedAt:0,feedbackMode:'event',recognizer});
output=[event,{...event,id:'hook',label:'hook',start_ms:750,end_ms:900}];
perEvent.update({timestamp:1000,valid:true});
assert.match(perEvent.feedback(1000),/^훅 1회/);
assert.equal(perEvent.feedback(1100),null);
output=[{...event,id:'again',start_ms:1100,end_ms:1500}];
perEvent.update({timestamp:1600,valid:true});
assert.equal(perEvent.feedback(1900),null);
assert.match(perEvent.feedback(2000),/^잽 1회/);
console.log('Motion round reset, score deduplication, feedback timing and immutable retry report passed');
